language: python

matrix:
  include:
    - python: 3.5
      env: PYVERSION=35
    - python: 3.6
      env: PYVERSION=36
    - python: 3.7
      sudo: true
      env: PYVERSION=37
    - os: linux
      dist: xenial
      script: - xvfb-run python setup.py test
    - os: windows

  allow_failures:
    - python: "3.7"

install:
  - pip install -q pytest pytest-runner pytest-cov coverage
  - pip install coveralls
  - pip install -e .[skl] # install skl dependencies

after_success:
  - "ls -lr htmlcov"
  - coveralls
