language: python
os: linux
dist: xenial

jobs:
  include:
    - python: 3.6
      env: PYVERSION=36
    - python: 3.7
      env: PYVERSION=37
    - python: 3.8
      env: PYVERSION=38

before_install:
  - sudo apt-get install jq
  - curl -LSs $(curl -LSs https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({name, browser_download_url} | select(.name | endswith(".jar"))) | .[0].browser_download_url')" -o codacy-coverage-reporter-assembly.jar

install:
  - pip install -q pytest pytest-runner pytest-cov coverage
  - pip install coveralls
  - pip install -e .[skl] # install skl dependencies

script:
  - xvfb-run python setup.py test

after_success:
  - "ls -lr htmlcov"
  - coveralls # coverage to coveralls.io
  - java -jar codacy-coverage-reporter-assembly.jar report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml # coverage to codacy.com
