language: python
python:
  - "3.6" # 3.7 not currently installable

install:
  # Install test requirements seperately
  - pip install -q pytest pytest-runner pytest-cov coverage
  - pip install coveralls
  - python setup.py install

before_script: # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - python setup.py test

after_success:
  - coveralls
